# Generated by Django 4.2.7 on 2023-12-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_point', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='display_order_in_questionnaire',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points_assigned_to_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='possible_question_dependencies',
        ),
        migrations.RemoveField(
            model_name='question',
            name='response_options',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='comments_on_response',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='response_to_question',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='score_assigned_to_response',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answeroption')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerOptions', to='main.question'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='question_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.questionresponse'),
        ),
    ]
