# Generated by Django 4.2.7 on 2023-12-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answeroption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.question'),
        ),
    ]
