# Generated by Django 4.2.7 on 2023-12-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_questionresponse_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('answer', 'questionnaire')},
        ),
    ]
