# Generated by Django 4.2.7 on 2023-12-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_questionnaire_date_of_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='date_of_questionnaire',
            field=models.DateField(),
        ),
    ]
