# Generated by Django 4.2.7 on 2023-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_questionnaire_date_of_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='addiction_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anxiety_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='average_hours_of_play_per_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='average_months_of_play',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='depression_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='excessive_sleepiness_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insomnia_score',
            field=models.IntegerField(null=True),
        ),
    ]
