# Generated by Django 4.2.7 on 2023-12-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_patient_addiction_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionnaireResponse',
        ),
    ]
