# Generated by Django 4.2.7 on 2023-12-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_questionnaireresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='addiction_level',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
