# Generated by Django 4.2.7 on 2023-12-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_patient_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together=set(),
        ),
    ]
