# Generated by Django 4.2.7 on 2023-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_questionresponse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='anxiety_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='average_hours_of_play_per_week',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='average_months_of_play',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='depression_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='excessive_sleepiness_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insomnia_score',
            field=models.FloatField(null=True),
        ),
    ]
