# Generated by Django 4.2.7 on 2023-12-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_date_of_birth'),
        ('main', '0013_alter_patient_anxiety_score_and_more'),
    ]

    operations = [
    ]
