# Generated by Django 4.1.1 on 2023-12-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_merge_20231209_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="planned_therapy_sessions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
