# Generated by Django 4.2.7 on 2023-12-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_chatmessage_thread_delete_message_chatmessage_thread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='date_of_questionnaire',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.patient')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.questiontype'),
        ),
    ]
