# Generated by Django 4.2.7 on 2023-12-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_question_questionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
