# Generated by Django 4.2.7 on 2023-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginCount',
            field=models.IntegerField(default=0),
        ),
    ]
