# Generated by Django 4.2.7 on 2023-12-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_logincount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loginCount',
            field=models.FloatField(default=0),
        ),
    ]
