# Generated by Django 4.2.7 on 2023-12-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_user_latest_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acount_type',
            field=models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('A', 'Admin')], max_length=20, null=True),
        ),
    ]
