# Generated by Django 4.2.7 on 2023-12-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_user_acount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acount_type',
            new_name='account_type',
        ),
    ]
