# Generated by Django 4.2.7 on 2024-01-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_alert_patient_alert_fromuser_alert_touser'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
