# Generated by Django 4.2.7 on 2024-01-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alert_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date_of_alert',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='toUser',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
