# Generated by Django 4.2.7 on 2024-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
