# Generated by Django 4.2.7 on 2024-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_feedback_email_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
