# Generated by Django 4.2.7 on 2024-01-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_feedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
